### ISSUE TITLE
More descriptive error message for API

### ISSUE THREAD

**Issue by afzalch** [Jailoodu/RestfulRegistration#2]
Description:
When testing registration API, I attempted to test when not providing any valid user id and the error message from the API doesn't make it clear as to the fact that the fault is due to an invalid user id. 

Severity:
Low

Environment
Windows Laptop
Docker Desktop

Expected:
No user with that id found

Actual:
`{"message": "Internal Server Error"}`

**Comment by Jailoodu** [comment]
Closing, because changes were made: https://github.com/Jailoodu/RestfulRegistration/commit/3d2c30369497103fb5777ae1826ebc54276609ab
